services:
 ap2:
   restart: unless-stopped
   network_mode: host
   build:
     context: ../
     dockerfile: docker/Dockerfile
   # In case we change from host mode and need to map ports.
   # ports:
     # - "7000:7000"
     # - "10000-10100:10000-10100/udp"
   volumes:
     - ../pairings:/airplay2/pairings/
   # devices:
   #  - "/dev/snd"
   environment: # All variables are optional.
     - AP2HOSTNAME=Office Speaker
     - AP2IFACE=eth0
     - NO_VOLUME_MANAGEMENT=true
